# Generated by Django 4.2.4 on 2023-08-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_document', models.FileField(upload_to='translated_documents/')),
                ('translation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
